### PR TITLE
feat: handle Scala 3

### PR DESCRIPTION
**Pull request by giurim**
I experimented with the plugin to support Scala 3 #31 . I was not able to come up with a nicer solution. Any suggestion?

### CODE REVIEW

**Comment by nathanalderson** [comment]
The approach here seems pretty reasonable. I'm not in the Scala world these days. If scala 3 artifacts are intended to all be binary compatible, though, then why not continue to use `_%%` as the suffix placeholder for both versions instead of introducing a new `%_3%` placeholder? It would hold `_3` for all scala 3 versions but `_2.xx` for scala two versions. Also, I assume the `%3%` placeholder is necessary because some libraries are sprinkling 3s about randomly in their version-3 artifact names?

Thanks for making progress on this.

**Comment by kbielefe** [comment]
One reason you might want a separate placeholder is that you can use 2.13 libraries in a 3.x project and vice versa. See [here](https://scala-lang.org/blog/2021/04/08/scala-3-in-sbt.html). In other words, if you are cross-compiling for 2.13 and 3.x, one of your dependencies might be 3.x for both versions of your build. I haven't looked in enough detail to know if this change adequately addresses that use case or not.

**Comment by nathanalderson** [comment]
In that case you could just explicitly list the dependency and version you wanted with no placeholders at all, right? You can also always fall back to doing more complicated logic in your gradle config using the variables provided by this plugin. For instance, this example from the README:

```
dependencies {
  if(scalaVersion.startsWith("2.12")) {
    compile "org.whatever:some-dependency:1.2.3"
  } else {
    compile "org.whatever:some-other-dependency:1.2.3"
  }
}
```

I'm still leaning toward `_%%` remaining as the only suffix placeholder.

**Comment by giurim** [comment]
> I'm still leaning toward `_%%` remaining as the only suffix placeholder.
I can see that it makes everything more clean. My problem is, that Scala 3 and 2.xx dependencies will be "duplicated" this way.

**Comment by nathanalderson** [comment]
@giurim Sorry if I'm missing the obvious. Can you share an example of the duplication you're talking about?  I'm not opposed to the new placeholder if it will be commonly useful.

**Comment by giurim** [comment]
This was the Gradle file I wanted to simplify:

```
dependencies {
    if(scalaVersion.startsWith("3.")) {
        implementation "org.scala-lang:scala3-library_3:%scala-version%"
        testImplementation "org.scalatest:scalatest_3:3.2.10"
    } else {
        implementation "org.scala-lang:scala-library:%scala-version%"
        testImplementation "org.scalatest:scalatest_%%:3.2.10"
    }
    testRuntimeOnly "org.junit.platform:junit-platform-engine:$junit_platform_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_platform_version"
}
```
With just recognizing "3" as scala major version it is still duplicated:
```
dependencies {
    if(scalaVersion.startsWith("3.")) {
        implementation "org.scala-lang:scala3-library_3:%scala-version%"
    } else {
        implementation "org.scala-lang:scala-library:%scala-version%"
    }
    testImplementation "org.scalatest:scalatest_%%:3.2.10"
    testRuntimeOnly "org.junit.platform:junit-platform-engine:$junit_platform_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_platform_version"
}
```
cannot use _%% on the Scala library above, because
- 2.x.x does not have a suffix at all
- 3.x.x library has a 3 in the name AND have a suffix

It is more than possible I miss something here. Also the library naming format for snapshot builds is different, but I did not even tried to figure that out.

**Comment by nathanalderson** [comment]
Yeah that all makes sense now. What if we did a sort of why-not-both approach?:

* `_%%` holds `_2.xx` or `_3` as appropriate.
* `%_3%` holds `_3` for 3.x.x versions or the empty string otherwise.
* `%3%` holds `3` for 3.x.x version or the empty string otherwise.

Should we also just provide a `%scala-library%` placeholder? It could calculate the whole string for you so you'd just need `implementation "%scala-library%"` in your `build.gradle`.

**Comment by giurim** [comment]
For the first part: I think thats what I tried to implement in the PR draft.

I was actually thinking about a solution like `implementation "%scala-library%"`  but in my mind it was more like a function, similar to repository shorthands, eg `mavenCentral()`. Also there are other scala-libs, like the compiler which have the same convention and might be needed.

**Comment by mdedetrich** [comment]
@giurim @nathanalderson I am guessing this PR is no longer being worked on, would it be okay if I took over (I can base my work ontop of this)?

**Comment by giurim** [comment]
All yours @mdedetrich and thank you!

**Comment by mdedetrich** [comment]
Ill see if I can commit directly onto your branch, if not then I will make a new PR based off your `giurim:scala3` branch so your work/attribution isn't lost.

**Comment by nathanalderson** [comment]
Just chiming in to say that although I'm not at ADTRAN or doing Scala work any more, I'm still happy to review a PR.

**Pull request closed without merging**
